version: '3'

services:
  profiledb:
    image: mysql:5.7.30
    container_name: profiledb
    ports:
      - "33061:3306"
#    command: --init-file /data/application/profile_ddl.sql
    volumes:
      - ./src/main/resources/profile_ddl.sql:/data/application/profile_ddl.sql
      - profile-data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: secret
      MYSQL_DATABASE: profiles
      MYSQL_USER: empuser
      MYSQL_PASSWORD: password
    networks:
      - backend

  profileapp:
    image: iainardo/m2k8s
    container_name: profileapp
    ports:
      - "8080:8080"
    volumes:
      - profile-images-data:/data
    environment:
      SPRING_APPLICATION_JSON: '{"spring.datasource.url":"jdbc:mysql://profiledb:3306/profiles?autoReconnect=true&useUnicode=true&characterEncoding=utf8&connectTimeout=30000&socketTimeout=6000000","spring.datasource.username":"empuser","spring.datasource.password":"password"}'
    depends_on:
      - profiledb
    networks:
      - backend


# Volumes
volumes:
  profile-data:
  profile-images-data:

networks:
  backend: